// The equilibrium-constrained inverse kinematics of `wiki/robot_model.md` 2.2,
// over sampled goal poses per tool, with the **two** oracles this route owes.
//
//   1. the forward-kinematics residual of 2.2, which gates this route exactly as
//      it gates the semi-analytic one -- a converged NLP whose answer does not
//      put the tool where it was asked for is a refusal naming the residual;
//   2. the equilibrium residual against `Model::passive_equilibrium`, which is
//      what makes the answer a genuine steady state and not merely a root of the
//      solver's own constraint.
//
// Both are re-evaluated here through the frozen model API rather than read off
// the residuals the solver reports, because a solver that reports its own
// residual is asserting nothing.
//
// Every sweep case is *generated by* forward kinematics from a configuration the
// description allows, with the passive pair already at the equilibrium of that
// configuration. So each goal is known by construction to have an
// equilibrium solution, and a refusal is a defect rather than a hard pose. The
// one case that deliberately has none is built the other way round and is a test
// of its own.
//
// Offline C++: no ROS, no DDS, no simulator is linked into this binary and none
// is reachable from it.

#include <gtest/gtest.h>

#include <algorithm>
#include <array>
#include <cmath>
#include <cstddef>
#include <iostream>
#include <limits>
#include <random>
#include <string>
#include <vector>

#include "crane_planning/equilibrium_ik.hpp"
#include "description_fixture.hpp"

namespace
{

using crane_planning_test::Machine;

/// How close to the slewing axis a sampled goal may be, m.
/**
 * The same exclusion the semi-analytic sweep states and for the same reason:
 * 2.2 step 1 is `q1 = atan2(y_d, x_d)`, which has no value on the axis itself,
 * and this route seeds from that one.
 */
constexpr double kAxisExclusion = 2.0;

/// How many reachable goals each tool is exercised over.
/**
 * Smaller than the semi-analytic sweep's 60 because a solve here costs that
 * one *plus* the NLP it seeds -- this route runs the fast route first. Twenty
 * five per tool is wide enough to catch a redundancy resolved outside the
 * telescope range or a converged solve that landed on the wrong root of
 * `g_u(q) = 0`, and keeps the binary inside its timeout.
 */
constexpr int kSamples = 25;

double wrap(double angle)
{
  return std::remainder(angle, 2.0 * M_PI);
}

double uniform(std::mt19937_64 & source, double lower, double upper)
{
  return std::uniform_real_distribution<double>(lower, upper)(source);
}

/// The actuated projection of a canonical eight-vector.
crane_model::QA actuated_of(const crane_model::Q & q)
{
  crane_model::QA q_a;
  for (std::size_t row = 0; row < crane_model::kActuatedDof; ++row) {
    q_a[static_cast<Eigen::Index>(row)] =
      q[static_cast<Eigen::Index>(crane_planning::kActuatedRows[row])];
  }
  return q_a;
}

/// The canonical eight of one actuated configuration, settled at its equilibrium.
bool settled_configuration(
  const crane_model::Model & model, const crane_model::QA & q_a,
  const crane_model::Payload & payload, crane_model::Q & q)
{
  auto settled = model.passive_equilibrium(q_a, payload);
  if (!settled.ok()) {
    return false;
  }
  q = crane_model::Q::Zero();
  for (std::size_t row = 0; row < crane_model::kActuatedDof; ++row) {
    q[static_cast<Eigen::Index>(crane_planning::kActuatedRows[row])] =
      q_a[static_cast<Eigen::Index>(row)];
  }
  q.segment<2>(4) = settled.value();
  return true;
}

/// A configuration inside the description's own ranges, with a margin.
crane_model::QA sample_configuration(
  std::mt19937_64 & source, const crane_planning::JointLimits & limits, double q8)
{
  crane_model::QA q_a = crane_model::QA::Zero();
  for (std::size_t row = 0; row < 4U; ++row) {
    const crane_planning::AxisLimit & axis = limits.axis[row];
    const double margin = 0.05 * (axis.upper - axis.lower);
    q_a[static_cast<Eigen::Index>(row)] =
      uniform(source, axis.lower + margin, axis.upper - margin);
  }
  q_a[0] = uniform(source, -2.5, 2.5);
  q_a[4] = uniform(source, -2.0, 2.0);
  q_a[5] = q8;
  return q_a;
}

struct Case
{
  crane_model::QA q_a;
  Eigen::Vector3d p_tcp_0;
  double phi_z{};
};

/// The goals one machine is exercised over, each known to have an equilibrium.
std::vector<Case> reachable_goals(
  const crane_model::Model & model, const crane_planning::JointLimits & limits, double q8,
  const crane_model::Payload & payload)
{
  std::mt19937_64 source(20260824U);
  std::vector<Case> cases;
  while (static_cast<int>(cases.size()) < kSamples) {
    Case sample;
    sample.q_a = sample_configuration(source, limits, q8);
    crane_model::Q q;
    if (!settled_configuration(model, sample.q_a, payload, q)) {
      continue;
    }
    auto pose = model.forward_kinematics(
      q, crane_model::Frame::MountingBase, crane_model::Frame::Tcp);
    if (!pose.ok()) {
      continue;
    }
    sample.p_tcp_0 = pose.value().position_m;
    if (sample.p_tcp_0.head<2>().norm() < kAxisExclusion) {
      continue;
    }
    sample.phi_z = crane_planning::phi_z_of(pose.value().orientation);
    cases.push_back(sample);
  }
  return cases;
}

/// An offset grasp: a payload with mass, held off the tilt axis.
/**
 * `wiki/robot_model.md` 5.1 in as many words -- an offset grasp *moves the
 * equilibrium*. A payload whose centre of mass sits on the hanging line adds
 * weight and nothing else, so it is the offset and not the mass alone that makes
 * the tool hang differently, and a test that used a centred one would assert
 * nothing.
 */
crane_model::Payload offset_grasp()
{
  crane_model::Payload payload;
  payload.valid = true;
  payload.mass_kg = 300.0;
  payload.center_of_mass_k8_m = Eigen::Vector3d(0.05, -0.02, 1.1);
  payload.inertia_k8_kg_m2.setZero();
  return payload;
}

}  // namespace

TEST(EquilibriumIk, EveryReachableGoalComesBackAsAGenuineSteadyState)
{
  for (const Machine & machine : crane_planning_test::machines()) {
    const crane_model::Model model = crane_planning_test::build_model(machine);
    const crane_planning::PlannerContext context =
      crane_planning_test::build_context(model, machine);
    const crane_planning::IkSettings & seed = context.settings.ik;
    const crane_planning::EquilibriumIkSettings & settings = context.settings.equilibrium;
    const crane_model::Payload payload = crane_planning_test::empty_gripper();
    const std::vector<Case> cases =
      reachable_goals(model, context.limits, machine.q8, payload);

    double worst_position = 0.0;
    double worst_yaw = 0.0;
    double worst_equilibrium = 0.0;
    std::size_t worst_iterations = 0;
    double worst_elapsed = 0.0;
    for (const Case & sample : cases) {
      crane_planning::IkRequest request;
      request.p_tcp_0 = sample.p_tcp_0;
      request.phi_z_d = sample.phi_z;
      request.q8 = machine.q8;
      request.payload = payload;

      auto solved = crane_planning::solve_equilibrium_constrained_ik(
        model, context.geometry, context.limits, seed, settings, request);
      if (!solved.ok()) {
        ADD_FAILURE() << machine.name << " refused q_a=" << sample.q_a.transpose() << ": "
                      << solved.status().message;
        continue;
      }
      const crane_planning::IkSolution & answer = solved.value();

      // Which of 2.2's two formulations produced this is carried on the answer.
      EXPECT_EQ(answer.route, crane_planning::EndpointRoute::EquilibriumConstrained)
        << machine.name;

      // Oracle one: the forward-kinematics acceptance test of 2.2, run again here
      // rather than trusted from the solver. It gates this route exactly as it
      // gates the semi-analytic one.
      auto pose = model.forward_kinematics(
        answer.q, crane_model::Frame::MountingBase, crane_model::Frame::Tcp);
      ASSERT_TRUE(pose.ok()) << machine.name;
      const double residual_p = (pose.value().position_m - sample.p_tcp_0).norm();
      const double residual_yaw = std::abs(
        wrap(crane_planning::phi_z_of(pose.value().orientation) - sample.phi_z));
      EXPECT_LT(residual_p, seed.eps_pos) << machine.name;
      EXPECT_LT(residual_yaw, seed.eps_yaw) << machine.name;

      // Oracle two, and the one that makes this route worth its cost: the passive
      // pair is the equilibrium of the actuated part that came out, not a value
      // pinned from outside and not the solver's own constraint residual restated.
      auto settled = model.passive_equilibrium(actuated_of(answer.q), payload);
      ASSERT_TRUE(settled.ok()) << machine.name;
      const double residual_equilibrium = (answer.q.segment<2>(4) - settled.value()).norm();
      EXPECT_LT(residual_equilibrium, settings.eps_equilibrium) << machine.name;

      // 2.2 step 3's redundancy is resolved on an extension the telescope has,
      // and the d45 reported is the one the answer was closed at.
      EXPECT_GE(answer.q[3], context.limits.axis[3].lower - 1.0e-9) << machine.name;
      EXPECT_LE(answer.q[3], context.limits.axis[3].upper + 1.0e-9) << machine.name;
      EXPECT_NEAR(context.geometry.d45(answer.q[3]), answer.d45, 1.0e-12) << machine.name;

      // And it stayed inside both caps, which is what makes it an answer rather
      // than the best iterate of a solve that ran out.
      EXPECT_LE(answer.nlp_iterations, settings.max_iterations) << machine.name;
      EXPECT_LE(answer.elapsed_s, settings.max_wall_clock_s) << machine.name;

      worst_position = std::max(worst_position, residual_p);
      worst_yaw = std::max(worst_yaw, residual_yaw);
      worst_equilibrium = std::max(worst_equilibrium, residual_equilibrium);
      worst_iterations = std::max(worst_iterations, answer.nlp_iterations);
      worst_elapsed = std::max(worst_elapsed, answer.elapsed_s);
    }

    std::cout << machine.name << ": " << cases.size() << " goals, worst residual "
              << worst_position << " m, " << worst_yaw << " rad, " << worst_equilibrium
              << " rad off equilibrium, worst " << worst_iterations << " iterations in "
              << worst_elapsed << " s" << std::endl;
  }
}

TEST(EquilibriumIk, AGoalTheArmReachesAndNoEquilibriumDoesIsRefused)
{
  // The goal every other case in this file is not: reachable geometrically, and
  // with no equilibrium solution at all. It is the **wrist's** own highest
  // reachable point, found over a grid in the description's own ranges, so a
  // configuration that puts K5 exactly there exists by construction and the point
  // is inside the geometric workspace 2.2 steps 1-2 close over. It is taken
  // beyond the slewing exclusion so that what refuses it is the equilibrium and
  // not 2.2 step 1's missing azimuth.
  //
  // No equilibrium reaches it, and the two measurements the argument needs are
  // taken here rather than assumed:
  //
  //   tcp_z  <=  tip_z - drop  <=  highest_tip_z - drop  <  goal.z()
  //
  // `highest_tip_z` is the grid maximum over *all* radii and `drop` the smallest
  // vertical distance from K5 to the tool over sampled equilibria. Measured, the
  // margin is some 0.2 m on both machines: the wrist reaches 13.56 m on the axis
  // and 13.28 m beyond the exclusion, while the tool hangs between 0.50 m and
  // 0.99 m below the wrist -- the spread is the K5-to-tilt offset turning with
  // q2 + q3, not the tool changing length.
  for (const Machine & machine : crane_planning_test::machines()) {
    const crane_model::Model model = crane_planning_test::build_model(machine);
    const crane_planning::PlannerContext context =
      crane_planning_test::build_context(model, machine);
    const crane_model::Payload payload = crane_planning_test::empty_gripper();

    // The wrist's reachable height, over a grid in (q2, q3, q4). K5 is upstream
    // of the passive tilt, so it does not move with q5 or q6 and forward
    // kinematics alone answers this -- no equilibrium solve enters the grid.
    double highest = -std::numeric_limits<double>::infinity();
    double goal_z = -std::numeric_limits<double>::infinity();
    Eigen::Vector3d goal = Eigen::Vector3d::Zero();
    constexpr int kBoomSteps = 25;
    constexpr int kTelescopeSteps = 9;
    for (int i2 = 0; i2 < kBoomSteps; ++i2) {
      for (int i3 = 0; i3 < kBoomSteps; ++i3) {
        for (int i4 = 0; i4 < kTelescopeSteps; ++i4) {
          const std::array<int, 3> step{{i2, i3, i4}};
          const std::array<int, 3> steps{{kBoomSteps - 1, kBoomSteps - 1, kTelescopeSteps - 1}};
          crane_model::Q q = crane_model::Q::Zero();
          for (std::size_t row = 1; row < 4U; ++row) {
            const crane_planning::AxisLimit & axis = context.limits.axis[row];
            q[static_cast<Eigen::Index>(row)] = axis.lower +
              (axis.upper - axis.lower) * step[row - 1U] / steps[row - 1U];
          }
          auto pose = model.forward_kinematics(
            q, crane_model::Frame::MountingBase, crane_model::Frame::Tip);
          if (!pose.ok()) {
            continue;
          }
          const Eigen::Vector3d p = pose.value().position_m;
          highest = std::max(highest, p.z());
          if (p.head<2>().norm() >= kAxisExclusion && p.z() > goal_z) {
            goal_z = p.z();
            goal = p;
          }
        }
      }
    }
    ASSERT_GT(goal_z, -std::numeric_limits<double>::infinity()) << machine.name;

    std::mt19937_64 source(1234U);
    double drop = std::numeric_limits<double>::infinity();
    for (int index = 0; index < 200; ++index) {
      const crane_model::QA q_a = sample_configuration(source, context.limits, machine.q8);
      crane_model::Q q;
      if (!settled_configuration(model, q_a, payload, q)) {
        continue;
      }
      auto tip = model.forward_kinematics(
        q, crane_model::Frame::MountingBase, crane_model::Frame::Tip);
      auto tcp = model.forward_kinematics(
        q, crane_model::Frame::MountingBase, crane_model::Frame::Tcp);
      ASSERT_TRUE(tip.ok() && tcp.ok()) << machine.name;
      drop = std::min(drop, tip.value().position_m.z() - tcp.value().position_m.z());
    }
    // The premise, asserted rather than assumed: if the tool ever reached as high
    // as the wrist, the goal below would be an ordinary reachable pose and this
    // test would be asserting nothing.
    ASSERT_GT(goal.z(), highest - drop) << machine.name
                                        << ": the hanging tool reaches the goal after all";

    crane_planning::IkRequest request;
    request.p_tcp_0 = goal;
    request.phi_z_d = 0.0;
    request.q8 = machine.q8;
    request.payload = payload;

    auto refused = crane_planning::solve_equilibrium_constrained_ik(
      model, context.geometry, context.limits, context.settings.ik,
      context.settings.equilibrium, request);
    ASSERT_FALSE(refused.ok())
      << machine.name << ": a goal " << goal.z() - (highest - drop)
      << " m above anything the hanging tool reaches was answered";
    // It says what it missed by, and it says that what it could not satisfy was
    // the goal and not the constraint -- which is the difference between an
    // unreachable placement and a broken solve.
    EXPECT_NE(refused.status().message.find("residual"), std::string::npos)
      << refused.status().message;
    EXPECT_NE(refused.status().message.find("no passive equilibrium"), std::string::npos)
      << refused.status().message;
  }
}

TEST(EquilibriumIk, ThePayloadEntersTheEquilibrium)
{
  // The `SHAPE_NONE` half of `crane_msgs/Payload` is an empty gripper -- mass
  // zero, valid true -- and the other half is a real block held off the tilt
  // axis. They hang the tool differently, so the configuration that puts K_tcp at
  // one pose is a different configuration; both put it at the *same* pose, to the
  // same tolerance. If the two came out equal in the passive pair, the payload
  // would not be entering the equilibrium at all.
  for (const Machine & machine : crane_planning_test::machines()) {
    const crane_model::Model model = crane_planning_test::build_model(machine);
    const crane_planning::PlannerContext context =
      crane_planning_test::build_context(model, machine);
    const crane_planning::IkSettings & seed = context.settings.ik;

    crane_model::QA q_a = crane_model::QA::Zero();
    for (std::size_t row = 0; row < 4U; ++row) {
      q_a[static_cast<Eigen::Index>(row)] = context.limits.axis[row].bounded ?
        context.limits.axis[row].centre() : 0.0;
    }
    q_a[0] = 0.4;
    q_a[5] = machine.q8;
    crane_model::Q q;
    ASSERT_TRUE(settled_configuration(model, q_a, crane_planning_test::empty_gripper(), q))
      << machine.name;
    auto pose = model.forward_kinematics(
      q, crane_model::Frame::MountingBase, crane_model::Frame::Tcp);
    ASSERT_TRUE(pose.ok()) << machine.name;

    crane_planning::IkRequest request;
    request.p_tcp_0 = pose.value().position_m;
    request.phi_z_d = crane_planning::phi_z_of(pose.value().orientation);
    request.q8 = machine.q8;

    request.payload = crane_planning_test::empty_gripper();
    auto empty = crane_planning::solve_equilibrium_constrained_ik(
      model, context.geometry, context.limits, seed, context.settings.equilibrium, request);
    request.payload = offset_grasp();
    auto carried = crane_planning::solve_equilibrium_constrained_ik(
      model, context.geometry, context.limits, seed, context.settings.equilibrium, request);
    ASSERT_TRUE(empty.ok()) << machine.name << ": " << empty.status().message;
    ASSERT_TRUE(carried.ok()) << machine.name << ": " << carried.status().message;

    // They hang differently.
    const double swing =
      (empty.value().q.segment<2>(4) - carried.value().q.segment<2>(4)).norm();
    EXPECT_GT(swing, 1.0e-4) << machine.name
                             << ": the payload did not move the passive pair at all";

    // And they agree on the tool pose, to the tolerance both were accepted on,
    // checked through forward kinematics rather than through the reports.
    for (const auto * answer : {&empty, &carried}) {
      auto placed = model.forward_kinematics(
        answer->value().q, crane_model::Frame::MountingBase, crane_model::Frame::Tcp);
      ASSERT_TRUE(placed.ok()) << machine.name;
      EXPECT_LT((placed.value().position_m - request.p_tcp_0).norm(), seed.eps_pos)
        << machine.name;
      EXPECT_LT(
        std::abs(wrap(crane_planning::phi_z_of(placed.value().orientation) - request.phi_z_d)),
        seed.eps_yaw) << machine.name;
    }

    // Each is the equilibrium of *its own* payload, which is the claim.
    auto empty_settled = model.passive_equilibrium(
      actuated_of(empty.value().q), crane_planning_test::empty_gripper());
    auto carried_settled =
      model.passive_equilibrium(actuated_of(carried.value().q), offset_grasp());
    ASSERT_TRUE(empty_settled.ok());
    ASSERT_TRUE(carried_settled.ok());
    EXPECT_LT(
      (empty.value().q.segment<2>(4) - empty_settled.value()).norm(),
      context.settings.equilibrium.eps_equilibrium) << machine.name;
    EXPECT_LT(
      (carried.value().q.segment<2>(4) - carried_settled.value()).norm(),
      context.settings.equilibrium.eps_equilibrium) << machine.name;
  }
}

TEST(EquilibriumIk, TheWallClockCapIsARefusalNamingTheCap)
{
  const Machine & machine = crane_planning_test::machines().front();
  const crane_model::Model model = crane_planning_test::build_model(machine);
  const crane_planning::PlannerContext context =
    crane_planning_test::build_context(model, machine);
  const crane_model::Payload payload = crane_planning_test::empty_gripper();
  const std::vector<Case> cases =
    reachable_goals(model, context.limits, machine.q8, payload);

  crane_planning::IkRequest request;
  request.p_tcp_0 = cases.front().p_tcp_0;
  request.phi_z_d = cases.front().phi_z;
  request.q8 = machine.q8;
  request.payload = payload;

  crane_planning::EquilibriumIkSettings settings = context.settings.equilibrium;
  settings.max_wall_clock_s = 1.0e-9;
  auto refused = crane_planning::solve_equilibrium_constrained_ik(
    model, context.geometry, context.limits, context.settings.ik, settings, request);
  ASSERT_FALSE(refused.ok()) << "a solve past its wall-clock cap returned an endpoint";
  EXPECT_NE(refused.status().message.find("wall-clock cap"), std::string::npos)
    << refused.status().message;

  // The same goal, with the deployed cap, is answered -- so what the refusal
  // above reports is the cap and not an unreachable goal.
  auto solved = crane_planning::solve_equilibrium_constrained_ik(
    model, context.geometry, context.limits, context.settings.ik,
    context.settings.equilibrium, request);
  EXPECT_TRUE(solved.ok()) << solved.status().message;
}

TEST(EquilibriumIk, TheIterationCapIsARefusalNamingTheCap)
{
  // A goal that is answered at the deployed cap and refused one iteration short
  // of what it actually took, so what separates the two runs is the cap alone.
  //
  // Which goal that is has to be found rather than written down. On the PZS100
  // every sampled goal converges in a single iteration -- its semi-analytic seed
  // is exact, because dq_eq/dq_a is [0, -1, -1, 0, 0] there and the tool hangs
  // vertically whatever the arm does -- so there is no cap below the deployed one
  // that machine can hit while still having an answer to give. The 7040's tool
  // sits off the tilt axis, its seed is only close, and the worst of twenty five
  // sampled goals took 24 iterations.
  bool exercised = false;
  for (const Machine & machine : crane_planning_test::machines()) {
    const crane_model::Model model = crane_planning_test::build_model(machine);
    const crane_planning::PlannerContext context =
      crane_planning_test::build_context(model, machine);
    const crane_model::Payload payload = crane_planning_test::empty_gripper();
    const std::vector<Case> cases =
      reachable_goals(model, context.limits, machine.q8, payload);

    for (const Case & sample : cases) {
      crane_planning::IkRequest request;
      request.p_tcp_0 = sample.p_tcp_0;
      request.phi_z_d = sample.phi_z;
      request.q8 = machine.q8;
      request.payload = payload;

      auto solved = crane_planning::solve_equilibrium_constrained_ik(
        model, context.geometry, context.limits, context.settings.ik,
        context.settings.equilibrium, request);
      if (!solved.ok() || solved.value().nlp_iterations < 2U) {
        continue;
      }

      crane_planning::EquilibriumIkSettings settings = context.settings.equilibrium;
      settings.max_iterations = solved.value().nlp_iterations - 1U;
      auto refused = crane_planning::solve_equilibrium_constrained_ik(
        model, context.geometry, context.limits, context.settings.ik, settings, request);
      ASSERT_FALSE(refused.ok())
        << machine.name << ": a solve stopped at " << settings.max_iterations
        << " of the " << solved.value().nlp_iterations << " iterations it needed still answered";
      EXPECT_NE(refused.status().message.find("iteration cap"), std::string::npos)
        << refused.status().message;
      EXPECT_NE(
        refused.status().message.find(std::to_string(settings.max_iterations)),
        std::string::npos) << refused.status().message;
      exercised = true;
      break;
    }
    if (exercised) {
      break;
    }
  }
  EXPECT_TRUE(exercised)
    << "no sampled goal needed more than one iteration on any machine, so the iteration cap "
       "was never reached and this test asserted nothing";
}

TEST(EquilibriumIk, AnUnboundedSolveIsRefusedOutright)
{
  const Machine & machine = crane_planning_test::machines().front();
  const crane_model::Model model = crane_planning_test::build_model(machine);
  const crane_planning::PlannerContext context =
    crane_planning_test::build_context(model, machine);

  crane_planning::IkRequest request;
  request.p_tcp_0 = Eigen::Vector3d(7.0, 1.0, 1.5);
  request.q8 = machine.q8;
  request.payload = crane_planning_test::empty_gripper();

  for (const bool iterations : {true, false}) {
    crane_planning::EquilibriumIkSettings settings = context.settings.equilibrium;
    if (iterations) {
      settings.max_iterations = 0U;
    } else {
      settings.max_wall_clock_s = 0.0;
    }
    auto refused = crane_planning::solve_equilibrium_constrained_ik(
      model, context.geometry, context.limits, context.settings.ik, settings, request);
    ASSERT_FALSE(refused.ok()) << (iterations ? "iterations" : "wall clock");
    EXPECT_NE(refused.status().message.find("hang"), std::string::npos)
      << refused.status().message;
  }
}

TEST(EquilibriumIk, AClearanceWeightWithNoReferenceToMeasureItAgainstIsRefused)
{
  // `robot_model` 2.2 step 3 scores the telescope redundancy by joint-range
  // centring *and* clearance. Both halves are real now, and what is refused is a
  // weight with nothing to measure against: every candidate would then score the
  // same and the second half of the score would vote for nothing.
  const Machine & machine = crane_planning_test::machines().front();
  const crane_model::Model model = crane_planning_test::build_model(machine);
  const crane_planning::PlannerContext context =
    crane_planning_test::build_context(model, machine);

  crane_planning::IkRequest request;
  request.p_tcp_0 = Eigen::Vector3d(7.0, 1.0, 1.5);
  request.q8 = machine.q8;
  request.payload = crane_planning_test::empty_gripper();

  crane_planning::EquilibriumIkSettings settings = context.settings.equilibrium;
  settings.redundancy.clearance = 1.0;
  settings.redundancy.clearance_reference_m = 0.0;
  auto refused = crane_planning::solve_equilibrium_constrained_ik(
    model, context.geometry, context.limits, context.settings.ik, settings, request);
  ASSERT_FALSE(refused.ok());
  EXPECT_NE(refused.status().message.find("reference clearance"), std::string::npos)
    << refused.status().message;
}
