// The semi-analytic inverse kinematics of `wiki/robot_model.md` 2.2, exercised
// over a sampled set of reachable poses per tool with the forward-kinematics
// residual as the oracle.
//
// Every case is *generated by* forward kinematics from a configuration the
// description allows, with the passive pair already at the equilibrium the
// solver will pin it at. So reachability is known by construction rather than
// assumed, and a solve that refuses a case is refusing a pose that certainly
// exists.
//
// The one region left out is a cylinder around the slewing axis, and it is left
// out because 2.2 step 1 is `q1 = atan2(y_d, x_d)`: on the axis itself the
// azimuth is not a number, and just off it an arbitrarily small change in the
// wrist target swings q1 through half a turn. That is a property of the method
// the wiki specifies, not of this implementation, and it is stated here rather
// than hidden in a tolerance.

#include <gtest/gtest.h>

#include <algorithm>
#include <cmath>
#include <cstddef>
#include <random>
#include <string>
#include <vector>

#include "crane_planning/inverse_kinematics.hpp"
#include "description_fixture.hpp"

namespace
{

using crane_planning_test::Machine;

/// How close to the slewing axis a sampled goal may be, m.
constexpr double kAxisExclusion = 2.0;

/// How many reachable poses each tool is exercised over.
constexpr int kSamples = 120;

double uniform(std::mt19937_64 & source, double lower, double upper)
{
  return std::uniform_real_distribution<double>(lower, upper)(source);
}

/// A configuration inside the description's own ranges, with a margin.
crane_model::QA sample_configuration(
  std::mt19937_64 & source, const crane_planning::JointLimits & limits, double q8)
{
  crane_model::QA q_a = crane_model::QA::Zero();
  for (std::size_t row = 0; row < 4U; ++row) {
    const crane_planning::AxisLimit & axis = limits.axis[row];
    const double margin = 0.05 * (axis.upper - axis.lower);
    q_a[static_cast<Eigen::Index>(row)] =
      uniform(source, axis.lower + margin, axis.upper - margin);
  }
  // The azimuth stays inside a half turn so that a sampled pose is not one the
  // rotator has to unwind through its own range to reach.
  q_a[0] = uniform(source, -2.5, 2.5);
  q_a[4] = uniform(source, -2.0, 2.0);
  q_a[5] = q8;
  return q_a;
}

struct Case
{
  crane_model::QA q_a;
  Eigen::Vector3d p_tcp_0;
  double phi_z{};
};

/// The reachable poses one machine is exercised over.
std::vector<Case> reachable_poses(
  const crane_model::Model & model, const crane_planning::JointLimits & limits, double q8,
  const crane_model::Payload & payload)
{
  std::mt19937_64 source(20260824U);
  std::vector<Case> cases;
  while (static_cast<int>(cases.size()) < kSamples) {
    Case sample;
    sample.q_a = sample_configuration(source, limits, q8);
    auto settled = model.passive_equilibrium(sample.q_a, payload);
    if (!settled.ok()) {
      continue;
    }
    crane_model::Q q = crane_model::Q::Zero();
    for (std::size_t row = 0; row < crane_model::kActuatedDof; ++row) {
      q[static_cast<Eigen::Index>(crane_planning::kActuatedRows[row])] =
        sample.q_a[static_cast<Eigen::Index>(row)];
    }
    q[4] = settled.value()[0];
    q[5] = settled.value()[1];
    auto pose = model.forward_kinematics(
      q, crane_model::Frame::MountingBase, crane_model::Frame::Tcp);
    if (!pose.ok()) {
      continue;
    }
    sample.p_tcp_0 = pose.value().position_m;
    if (sample.p_tcp_0.head<2>().norm() < kAxisExclusion) {
      continue;  // 2.2 step 1 has no azimuth here; see the file header
    }
    sample.phi_z = crane_planning::phi_z_of(pose.value().orientation);
    cases.push_back(sample);
  }
  return cases;
}

crane_model::Payload empty_gripper()
{
  crane_model::Payload payload;
  payload.valid = true;
  payload.mass_kg = 0.0;
  payload.inertia_k8_kg_m2.setZero();
  return payload;
}

}  // namespace

TEST(InverseKinematics, EveryReachablePoseIsSolvedWithinTheAcceptanceResidual)
{
  for (const Machine & machine : crane_planning_test::machines()) {
    const crane_model::Model model = crane_planning_test::build_model(machine);
    const crane_planning::PlannerContext context =
      crane_planning_test::build_context(model, machine);
    const crane_model::Payload payload = empty_gripper();
    const std::vector<Case> cases =
      reachable_poses(model, context.limits, machine.q8, payload);

    double worst_position = 0.0;
    double worst_yaw = 0.0;
    int refused = 0;
    for (const Case & sample : cases) {
      crane_planning::IkRequest request;
      request.p_tcp_0 = sample.p_tcp_0;
      request.phi_z_d = sample.phi_z;
      request.q8 = machine.q8;
      request.payload = payload;

      auto solved = crane_planning::solve_inverse_kinematics(
        model, context.geometry, context.limits, context.settings.ik, request);
      if (!solved.ok()) {
        ++refused;
        // A refusal has to say what it refused on, because a caller that cannot
        // see the residual cannot tell a hard pose from a broken solver.
        EXPECT_NE(solved.status().message.find("residual"), std::string::npos)
          << solved.status().message;
        continue;
      }
      worst_position = std::max(worst_position, solved.value().residual_p);
      worst_yaw = std::max(worst_yaw, solved.value().residual_phi_z);

      // The oracle, run again here rather than trusted from the solver: the
      // whole claim of 2.2 is that the answer is validated against forward
      // kinematics before it is used.
      auto pose = model.forward_kinematics(
        solved.value().q, crane_model::Frame::MountingBase, crane_model::Frame::Tcp);
      ASSERT_TRUE(pose.ok()) << machine.name;
      EXPECT_LT((pose.value().position_m - sample.p_tcp_0).norm(), context.settings.ik.eps_pos)
        << machine.name;
      EXPECT_LT(
        std::abs(
          std::remainder(
            crane_planning::phi_z_of(pose.value().orientation) - sample.phi_z, 2.0 * M_PI)),
        context.settings.ik.eps_yaw) << machine.name;

      // And the passive pair really is at the equilibrium 2.2 pins it at.
      auto settled = model.passive_equilibrium(sample.q_a, payload);
      ASSERT_TRUE(settled.ok());
      auto solved_equilibrium =
        model.passive_equilibrium(
        crane_model::QA(
          (crane_model::QA() << solved.value().q[0], solved.value().q[1], solved.value().q[2],
          solved.value().q[3], solved.value().q[6], solved.value().q[7]).finished()),
        payload);
      ASSERT_TRUE(solved_equilibrium.ok());
      EXPECT_LT(
        (solved.value().q.segment<2>(4) - solved_equilibrium.value()).norm(), 1.0e-6)
        << machine.name;
    }

    std::cout << machine.name << ": " << cases.size() - static_cast<std::size_t>(refused)
              << "/" << cases.size() << " reachable poses solved, worst residual "
              << worst_position << " m and " << worst_yaw << " rad" << std::endl;
    EXPECT_EQ(refused, 0) << machine.name << ": " << refused
                          << " reachable poses were refused";
  }
}

TEST(InverseKinematics, TheRedundancyIsResolvedInsideTheTelescopeRange)
{
  for (const Machine & machine : crane_planning_test::machines()) {
    const crane_model::Model model = crane_planning_test::build_model(machine);
    const crane_planning::PlannerContext context =
      crane_planning_test::build_context(model, machine);
    const crane_model::Payload payload = empty_gripper();
    const std::vector<Case> cases =
      reachable_poses(model, context.limits, machine.q8, payload);

    for (const Case & sample : cases) {
      crane_planning::IkRequest request;
      request.p_tcp_0 = sample.p_tcp_0;
      request.phi_z_d = sample.phi_z;
      request.q8 = machine.q8;
      request.payload = payload;
      auto solved = crane_planning::solve_inverse_kinematics(
        model, context.geometry, context.limits, context.settings.ik, request);
      if (!solved.ok()) {
        continue;
      }
      const double q4 = solved.value().q[3];
      EXPECT_GE(q4, context.limits.axis[3].lower - 1.0e-9) << machine.name;
      EXPECT_LE(q4, context.limits.axis[3].upper + 1.0e-9) << machine.name;
      EXPECT_NEAR(context.geometry.d45(q4), solved.value().d45, 1.0e-12) << machine.name;
    }
  }
}

TEST(InverseKinematics, AGoalOutsideTheTwoLinkWorkspaceIsRefused)
{
  const Machine & machine = crane_planning_test::machines().front();
  const crane_model::Model model = crane_planning_test::build_model(machine);
  const crane_planning::PlannerContext context =
    crane_planning_test::build_context(model, machine);

  crane_planning::IkRequest request;
  request.p_tcp_0 = Eigen::Vector3d(500.0, 0.0, 0.0);
  request.q8 = machine.q8;
  request.payload = empty_gripper();

  auto refused = crane_planning::solve_inverse_kinematics(
    model, context.geometry, context.limits, context.settings.ik, request);
  ASSERT_FALSE(refused.ok());
  EXPECT_NE(refused.status().message.find("workspace"), std::string::npos)
    << refused.status().message;
}

TEST(InverseKinematics, ACarriedPayloadMovesTheEndpointItSolvesFor)
{
  // robot_model 5.1: an offset grasp does not merely add mass, it tilts the tool
  // at rest -- so the configuration that puts K_tcp at one pose with an empty
  // gripper is not the configuration that puts it there with a block hanging
  // off-centre. If the two came out the same, the payload would not be reaching
  // the equilibrium at all.
  const Machine & machine = crane_planning_test::machines().front();
  const crane_model::Model model = crane_planning_test::build_model(machine);
  const crane_planning::PlannerContext context =
    crane_planning_test::build_context(model, machine);

  crane_model::Payload offset_grasp;
  offset_grasp.valid = true;
  offset_grasp.mass_kg = 300.0;
  offset_grasp.center_of_mass_k8_m = Eigen::Vector3d(0.05, -0.02, 1.1);
  offset_grasp.inertia_k8_kg_m2.setZero();

  crane_planning::IkRequest request;
  request.p_tcp_0 = Eigen::Vector3d(7.0, 1.0, 1.5);
  request.phi_z_d = 0.3;
  request.q8 = machine.q8;

  request.payload = empty_gripper();
  auto without = crane_planning::solve_inverse_kinematics(
    model, context.geometry, context.limits, context.settings.ik, request);
  request.payload = offset_grasp;
  auto with = crane_planning::solve_inverse_kinematics(
    model, context.geometry, context.limits, context.settings.ik, request);
  ASSERT_TRUE(without.ok()) << without.status().message;
  ASSERT_TRUE(with.ok()) << with.status().message;

  EXPECT_GT((without.value().q - with.value().q).norm(), 1.0e-6);
  // Both still put the tool where it was asked for; that is the point.
  EXPECT_LT(without.value().residual_p, context.settings.ik.eps_pos);
  EXPECT_LT(with.value().residual_p, context.settings.ik.eps_pos);
}
