// The tool coordinate q8, driven on the **retained** grip cosine primitive of
// `wiki/trajectory_planning.md` 8 and timed on the arm's own clock.
//
// 8's replacement table is the one row of that table that keeps what it found:
// "Grip trajectory cosine primitives -> retained as a structured primitive
// (4.4)". So what changes about a grip is not the shape of the tool coordinate
// but where its clock comes from and which limits it is held inside. 4.1 states
// both:
//
//   "The tool coordinate q8 is **not a path variable** ... It is nevertheless
//    part of the reference ... generated by the grip primitive and concatenated
//    on the same time base. Geometrically the tool is decoupled from the arm;
//    temporally it is not, and the two must share one clock."
//
// This file is the grip primitive. It emits a `TimedTrajectory` over the same
// six actuated rows and the same sample period `solve_timing_ocp` emits, with
// the five path coordinates held at the measured start and q8 alone moving --
// so a close phase and an arm phase are two answers on one time base, not two
// schedules that happen to be handed to the same controller.
//
// # Why the cosine is on the rate and not on the position
//
// The legacy primitive is a raised cosine in position, and a raised cosine in
// position is `C1` at its ends and not `C2`: its second derivative there is
// `pi^2 |travel| / 2 T^2` and not zero, so the tool coordinate starts with a
// step in acceleration. Everything else this planner emits meets its ends with
// `q_a' = q_a'' = 0` (`geometric_path.hpp`), and a reference whose sixth row
// alone steps in acceleration at `t = 0` is a reference the velocity
// controller's own spline fit has to absorb.
//
// The cosine is therefore carried on the **rate**,
//
//     h'(s) = 1 - cos(2 pi s),      h(s) = s - sin(2 pi s) / (2 pi),
//
// which is the same primitive one integral up: still a cosine, still one
// parameter, and now `h(0) = h'(0) = h''(0) = 0` and `h(1) = 1`,
// `h'(1) = h''(1) = 0`. It is monotone, because `h' >= 0` everywhere, so a close
// never opens on its way to closing.
//
// # Which end of the range closes the gripper is **not** in the description
//
// The description gives the tool axis a range and a velocity limit and says
// nothing about which end of that range is a closed gripper. That is a property
// of the mounted tool, and this workspace has evidence for one of the two:
//
//   * **7040 jaw**, `theta10_outer_jaw_joint`, 0 ... 3.15 rad. Issue 037's notes
//     measured `jaw_stroke(q8).ratio` across the range and record that "the
//     cylinder retracts as the outer jaw opens", with the ratio negative at
//     `q8 = 0`. The range therefore starts at the jaws together: **lower is
//     closed**, and it is measured rather than assumed.
//   * **PZS100 rail gripper**, `q9_left_rail_joint`, 0.2 ... 0.7 m. Nothing in
//     this workspace records which way the rails run.
//     `wiki/implementation/commissioning_prerequisites.md` item 4 already owns
//     that axis as human work. `ToolAxisSettings::closed_end` therefore defaults
//     to `Lower` for both -- the reading a rail pair whose coordinate starts at
//     0.2 m and opens outward has -- and it is a **parameter**, exactly as
//     `system_pressure_pa` is a parameter, so a deployment that measures its own
//     tool replaces it instead of patching this file.
//
// # The limits a tool phase is held inside, and the one it is not
//
// The tool axis's **own** velocity limit off the description, its own
// acceleration limit out of `wiki/implementation/parameters.md` 3, and the pump
// flow of `wiki/mpc.md` 3 constraint 7 -- the last through
// `Model::transmission`, which is `Q_i = A_i^{+-}(v_i) |v_i|` and is the numeric
// twin of the expression the OCP reads off the symbolic graph. All three carry
// the same `kappa` of `wiki/trajectory_planning.md` 5.5 the arm phases carry,
// and `speed_scale` multiplies the velocity bound alone, so no caller reaches
// into the margin here either.
//
// **The cylinder force is deliberately not among them.** Constraint 6 bounds the
// force an axis spends *moving*; what a close phase ends in is a clamping force
// on the payload, which is the whole purpose of the axis and is not a violation
// of anything. Holding a grip to `kappa F^max` would refuse every grip that
// gripped.
//
// # The 7040 jaw's transmission reverses sign inside its own range
//
// Issue 037's notes measured the crossing at `q8 ~= 0.29 rad`, well inside the
// URDF's `0 ... 3.15`. At the crossing `J_c,GR = 0`: the cylinder moves the jaw
// through no distance at all, so the axis is not controllable there and a
// velocity command has no cylinder velocity that produces it. A phase whose
// travel spans the crossing is **refused naming it**, with the largest travel on
// the start's own side of it in the message. It is not clipped and not planned
// through: a close that stopped at the toggle and reported success would be the
// silent stub the model API contract exists to prevent.
//
// The PZS100's rail cylinder is one-to-one with q8 over the whole range, so
// nothing crosses there and a full close or open is planned.

#ifndef CRANE_PLANNING__TOOL_AXIS_HPP_
#define CRANE_PLANNING__TOOL_AXIS_HPP_

#include <cstddef>
#include <cstdint>
#include <string>

#include "crane_model/model.hpp"
#include "crane_planning/joint_limits.hpp"
#include "crane_planning/timing_ocp.hpp"
#include "crane_planning/trajectory_timing.hpp"

namespace crane_planning
{

/// Which end of the range the description gives the tool axis closes the gripper.
enum class ToolEnd : std::uint8_t
{
  Lower,
  Upper
};

[[nodiscard]] const char * tool_end_name(ToolEnd end) noexcept;

/// What a deployment knows about the mounted tool's own axis. See the header.
struct ToolAxisSettings
{
  /// Measured on the 7040 (issue 037's notes), assumed on the PZS100.
  ToolEnd closed_end{ToolEnd::Lower};

  /// How densely `J_c,GR` is probed across a phase's travel.
  /**
   * The 7040's jaw ratio is a smooth four-bar function of q8 alone and crosses
   * zero once over the URDF's range, so this is a resolution for locating that
   * crossing and not a convergence criterion: the sign change is bracketed on
   * this grid and then bisected.
   */
  std::size_t transmission_samples{65};

  /// `|J_c,GR|` at or below which the axis counts as toggled, m/rad or m/m.
  /**
   * A ratio of zero is the toggle exactly; a ratio a thousandth of the way to it
   * is an axis whose cylinder has to move a millimetre to turn the jaw by a
   * radian, which no valve resolves. Both are refused for the same reason and
   * with the same message.
   */
  double transmission_floor{1.0e-3};

  /// Shortest travel that is a move rather than a gripper already where it was asked for.
  double min_travel{1.0e-9};
};

/// Where a close or an open phase drives the tool coordinate to.
/**
 * The end of the range the **description** gives the axis, picked by
 * `closed_end`. An axis the description leaves unbounded has no such end and is
 * refused rather than given an invented one -- both machine descriptions in this
 * workspace bound it.
 */
[[nodiscard]] crane_model::Result<double> tool_axis_target(
  const JointLimits & limits, ToolEnd closed_end, bool closing);

/// The retained cosine primitive of 8, as `h`, `h'` and `h''` on `s` in [0, 1].
/**
 * `h(s) = s - sin(2 pi s) / (2 pi)`. See the header for why the cosine sits on
 * the rate: this is the lowest form of it that is `C2` at both ends, which is
 * what puts the tool coordinate on the same footing as the five path
 * coordinates `geometric_path.hpp` fits.
 */
[[nodiscard]] double grip_cosine(double s) noexcept;
[[nodiscard]] double grip_cosine_rate(double s) noexcept;
[[nodiscard]] double grip_cosine_curvature(double s) noexcept;

/// Peak `h'` and peak `|h''|` of the primitive above, as exact constants.
/**
 * `h'` peaks at `s = 1/2` and `|h''|` at `s = 1/4` and `s = 3/4`. They are the
 * whole of the timing: a phase of travel `d` over `T` seconds reaches
 * `d kGripCosinePeakRate / T` and `d kGripCosinePeakCurvature / T^2`.
 */
inline constexpr double kGripCosinePeakRate = 2.0;
inline constexpr double kGripCosinePeakCurvature = 6.283185307179586;  // 2 pi

/// Where the tool axis's transmission ratio reverses sign inside a travel.
struct TransmissionCrossing
{
  bool crossed{false};
  double q8{};             ///< where `J_c,GR` passes through zero, rad or m
  double ratio_lower{};    ///< the ratio at the lower end of the travel
  double ratio_upper{};    ///< and at the upper end
  double smallest_ratio{}; ///< the smallest `|J_c,GR|` the probe saw
};

/// Probe `J_c,GR` across one travel of the tool coordinate.
/**
 * `Model::cylinder_jacobian` is diagonal and its tool row is a function of q8
 * alone -- constant on the PZS100's one-to-one rail cylinder, the four-bar of
 * `wiki/hydraulics.md` 2.6 on the 7040's jaw -- so the arm and the passive pair
 * enter only as the pose the row is evaluated at. `q` is therefore taken once
 * from the caller and only its tool coordinate is swept. `test_tool_axis.cpp`
 * asserts that independence rather than assuming it.
 */
[[nodiscard]] crane_model::Result<TransmissionCrossing> probe_tool_transmission(
  const crane_model::Model & model, const crane_model::Q & q, double q8_from, double q8_to,
  const ToolAxisSettings & settings);

/// What one tool phase costs the machine, against the **physical** limits.
/**
 * Fractions of the unscaled limit, on the same terms `PeakDemand` reports the
 * OCP's: a phase built at `kappa = 0.8` reports peaks at or below 0.8, so the
 * margin is something a caller reads rather than trusts.
 */
struct ToolAxisDemand
{
  double travel{};                ///< `q8_goal - q8_start`, signed, rad or m
  double duration{};              ///< s
  double peak_rate{};             ///< `|dq8|`, rad/s or m/s
  double peak_acceleration{};     ///< `|ddq8|`, rad/s^2 or m/s^2
  double peak_flow{};             ///< m^3/s, `Model::transmission`'s own Q for this axis
  double flow_per_unit_rate{};    ///< the worst `Q / |dq8|` over the travel, m^3
  double smallest_ratio{};        ///< the smallest `|J_c,GR|` over the travel
  double velocity_fraction{};     ///< of the description's own `dq8^max`
  double acceleration_fraction{}; ///< of `ddq_a^max` for the tool row
  double flow_fraction{};         ///< of `Q_P^max`, before the planning factor
  bool velocity_binding{false};   ///< which of the four chose the duration
  bool acceleration_binding{false};
  bool flow_binding{false};
  bool duration_floor_binding{false};
};

/// One close or open phase, answered.
struct ToolPhase
{
  TimedTrajectory trajectory{};
  ToolAxisDemand demand{};
  double q8_start{};
  double q8_goal{};
  ToolEnd closed_end{ToolEnd::Lower};
  bool closing{false};

  /// Where the tool hangs at each end, with the request's payload.
  /**
   * Carried out rather than kept inside, because it is the only surface on which
   * "the payload is honoured" is checkable: the emitted reference is six
   * actuated rows and a payload held off the tilt axis moves the **passive**
   * pair (`wiki/robot_model.md` 5.1), which no actuated row shows.
   */
  crane_model::QU q_u_start{crane_model::QU::Zero()};
  crane_model::QU q_u_goal{crane_model::QU::Zero()};
};

/// What one tool phase is asked for.
struct ToolAxisRequest
{
  crane_model::QA q_a_start{crane_model::QA::Zero()};  ///< where the machine is now
  double q8_goal{};                                    ///< where this phase drives the tool
  crane_model::Payload payload{};

  /// `crane_msgs/PlanGrip.speed_scale`, in (0, 1]. **Not** kappa.
  double speed_scale{1.0};

  /// kappa of 5.5, the same reservation the arm phases carry.
  double kappa{0.8};

  ActuationLimits actuation{};   ///< `ddq_a^max` for the tool row, and `Q_P^max`
  double sample_period{0.04};    ///< the arm's own emitted grid, s
  double min_duration{0.5};      ///< the same floor `RampSettings` puts on a ramp, s
};

/// Drive q8 from where it is to where the phase asks, or refuse and say why.
[[nodiscard]] crane_model::Result<ToolPhase> drive_tool_axis(
  const crane_model::Model & model, const JointLimits & limits,
  const ToolAxisSettings & settings, const ToolAxisRequest & request);

/// The phase in one sentence, for the service response.
[[nodiscard]] std::string describe(const ToolPhase & phase);

}  // namespace crane_planning

#endif  // CRANE_PLANNING__TOOL_AXIS_HPP_
