#!/usr/bin/env python3
"""
Code-generate the trajectory OCP that `crane_planning.ocp` defines.

The problem is *not* here: it is `crane_planning/ocp.py`'s `build_ocp`, because
this package solves it from Python and a definition beside the exporter would be
a second copy. What is here is the command line and the tree it writes.

    ./scripts/export_timing_ocp.py            # rewrite `generated/`
    ./scripts/export_timing_ocp.py --check    # regenerate into a scratch tree and diff
    ./scripts/export_timing_ocp.py --description live.urdf --compile-only

The third is the prep step for a run: it compiles a solver for the machine the
node will actually be handed on `/robot_description` and leaves `generated/`
alone. Without it the node quits on the description it is handed, because the
only solver it could load would be one baked for some *other* description.

Dump the description off a running deployment, then compile against it:

    ./scripts/dump_robot_description.py live.urdf
    ./scripts/export_timing_ocp.py --description live.urdf --compile-only
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

PACKAGE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PACKAGE.parent / "crane_ocp" / "scripts"))
sys.path.insert(0, str(PACKAGE))

import crane_ocp_export as ox  # noqa: E402
from acados_template import AcadosOcpSolver  # noqa: E402
from crane_planning.ocp import (  # noqa: E402
    CACHE,
    DESCRIPTION,
    GENERATED_HEADER,
    H_ACCEL,
    H_COMMAND,
    H_FLOW,
    H_RATE,
    H_SWAY,
    HE_SWAY,
    HE_SWAY_RATE,
    NH,
    NH_E,
    X_HORIZON,
    build_ocp,
    cache_key,
    tree_of,
    write_manifest,
)

# ------------------------------------------------------------------ generation


README = """\
# generated

`scripts/export_timing_ocp.py` writes this tree. Do not edit it; re-run the
script. `--check` regenerates into a scratch tree and diffs, which is what CI
runs.

The horizon, the weights `W`, every box and every `L1` slack price are set on the
generated solver at run time, so moving any of them needs no re-export. What is
baked is the **structure**: the residual rows and their scaling, the row order of
`h`, and the description the dynamics were built from.
"""


def write_header(output: Path, parameters: dict, scale: np.ndarray) -> Path:
    """Write the row offsets and divisors the caller must agree with, not invent."""
    path = output / GENERATED_HEADER
    guard = "CRANE_PLANNING_OCP_GENERATED_H_"
    divisors = ", ".join(f"{value!r}" for value in scale.tolist())
    path.write_text(
        "\n".join(
            [
                "// Generated by `scripts/export_timing_ocp.py`. Do not edit.",
                f"#ifndef {guard}",
                f"#define {guard}",
                "",
                f"#define CRANE_PLANNING_OCP_INTERVALS {int(parameters['ocp_intervals'])}",
                "// T = x[CRANE_PLANNING_OCP_X_HORIZON] * CRANE_PLANNING_OCP_HORIZON_S.",
                f"#define CRANE_PLANNING_OCP_X_HORIZON {X_HORIZON}",
                f"#define CRANE_PLANNING_OCP_HORIZON_S {float(parameters['ocp_horizon'])!r}",
                "",
                f"#define CRANE_PLANNING_OCP_H_SWAY {H_SWAY}",
                f"#define CRANE_PLANNING_OCP_H_FLOW {H_FLOW}",
                f"#define CRANE_PLANNING_OCP_H_RATE {H_RATE}",
                f"#define CRANE_PLANNING_OCP_H_ACCEL {H_ACCEL}",
                f"#define CRANE_PLANNING_OCP_H_COMMAND {H_COMMAND}",
                f"#define CRANE_PLANNING_OCP_NH {NH}",
                f"#define CRANE_PLANNING_OCP_HE_SWAY {HE_SWAY}",
                f"#define CRANE_PLANNING_OCP_HE_SWAY_RATE {HE_SWAY_RATE}",
                f"#define CRANE_PLANNING_OCP_NH_E {NH_E}",
                "",
                f"#define CRANE_PLANNING_OCP_SCALE {{{divisors}}}",
                "",
                f"#endif  // {guard}",
                "",
            ]
        )
    )
    return path


def generate(
    output: Path, description: str, parameters: dict, hydraulics: dict
) -> None:
    """Write the whole tree, from an empty directory."""
    output.mkdir(parents=True, exist_ok=True)
    ocp, scale, model = build_ocp(description, parameters, hydraulics)
    tree = ox.generate_solver(ocp, output)
    ox.write_output_map(model, ocp.model.name, tree)
    write_header(output, parameters, scale)
    ox.finalise(output, README)


def compile_solver(description: str, parameters: dict, hydraulics: dict) -> None:
    """
    Compile the solver into the cache the planner loads from.

    Exporting without this leaves the node with nothing to load: it refuses the
    description rather than pay for a code generation and a C build -- thirteen
    seconds on a warm toolchain and minutes on a cold one -- inside whatever asked
    for the plan. Doing it here means a node is ready when it starts.

    It is a second `build_ocp` and a second code generation on purpose: what
    `output` gets is the pruned, normalised tree `--check` reviews, and
    `crane_ocp`'s `finalise` reads every file it ships as text, so a compiled
    `.so` cannot live there. Same problem, two artifacts.
    """
    ocp, _, _ = build_ocp(description, parameters, hydraulics)
    CACHE.mkdir(parents=True, exist_ok=True)
    # Named by what is baked, not by the tool alone: a cached `.so` is loaded and
    # not compared, so a changed `path_segments`, integrator or *description* has
    # to land in a different directory or the node answers with the previous
    # build. The node hashes the description it was handed on `/robot_description`
    # and says which of these it missed on, so compiling for the wrong machine is
    # a warning at run time rather than a silent wrong answer.
    key = cache_key(parameters, hydraulics, description)
    tree = tree_of(key)
    ocp.code_export_directory = str(tree)
    AcadosOcpSolver(ocp, json_file=str(tree.with_suffix(".json")), verbose=False)
    write_manifest(tree, key)
    print(f"compiled {tree} (description sha1 {key['description'][:10]})")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ox.add_arguments(parser, PACKAGE)
    parser.add_argument(
        "--no-compile",
        action="store_true",
        help="write the tree but do not compile the solver into the cache",
    )
    parser.add_argument(
        "--description",
        type=Path,
        help=(
            "the machine to bake, instead of the test fixture. What the node "
            "plans for is whatever `/robot_description` carries, which in sim is "
            "a different xacro than the fixture; dump it byte for byte with "
            "`scripts/dump_robot_description.py`. Needs --compile-only"
        ),
    )
    parser.add_argument(
        "--compile-only",
        action="store_true",
        help=(
            "compile into the cache and leave `generated/` alone -- the prep "
            "step for a live description, which must not rewrite the shipped tree"
        ),
    )
    arguments = parser.parse_args()

    parameters = ox.read_ros_parameters(
        PACKAGE / "config" / "crane_planner.yaml", "crane_planner"
    )
    source = arguments.description or arguments.descriptions / DESCRIPTION
    description = source.read_text()
    # `generated/` is the shipped tree `--check` and CI diff against, and they
    # regenerate it from the fixture. Writing another machine into it would make
    # every later `--check` report a diff nobody asked for.
    if arguments.description and not arguments.compile_only:
        parser.error("--description writes only into the cache: add --compile-only")
    if arguments.compile_only:
        compile_solver(description, parameters, parameters)
        return 0
    status = ox.run(
        arguments.output,
        arguments.check,
        lambda output: generate(output, description, parameters, parameters),
        "export_timing_ocp.py",
    )
    # `--check` compares two trees and must not touch the cache; a real export
    # leaves a compiled solver behind so the node does not build one on demand.
    if status == 0 and not arguments.check and not arguments.no_compile:
        compile_solver(description, parameters, parameters)
    return status


if __name__ == "__main__":
    sys.exit(main())
