#!/usr/bin/env python3
"""
Code-generate the trajectory OCP that `crane_planning.ocp` defines.

The problem is *not* here: it is `crane_planning/ocp.py`'s `build_ocp`, because
this package solves it from Python and a definition beside the exporter would be
a second copy. What is here is the command line and the tree it writes.

    ./scripts/export_timing_ocp.py            # rewrite `generated/`
    ./scripts/export_timing_ocp.py --check    # regenerate into a scratch tree and diff
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

PACKAGE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PACKAGE.parent / "crane_ocp" / "scripts"))
sys.path.insert(0, str(PACKAGE))

import crane_ocp_export as ox  # noqa: E402
from crane_planning.ocp import (  # noqa: E402
    DESCRIPTION,
    GENERATED_HEADER,
    H_FLOW,
    H_SWAY,
    HE_SWAY,
    HE_SWAY_RATE,
    NH,
    NH_E,
    X_HORIZON,
    build_ocp,
)

# ------------------------------------------------------------------ generation


README = """\
# generated

`scripts/export_timing_ocp.py` writes this tree. Do not edit it; re-run the
script. `--check` regenerates into a scratch tree and diffs, which is what CI
runs.

The horizon, the weights `W`, every box and every `L1` slack price are set on the
generated solver at run time, so moving any of them needs no re-export. What is
baked is the **structure**: the residual rows and their scaling, the row order of
`h`, and the description the dynamics were built from.
"""


def write_header(output: Path, parameters: dict, scale: np.ndarray) -> Path:
    """Write the row offsets and divisors the caller must agree with, not invent."""
    path = output / GENERATED_HEADER
    guard = "CRANE_PLANNING_OCP_GENERATED_H_"
    divisors = ", ".join(f"{value!r}" for value in scale.tolist())
    path.write_text(
        "\n".join(
            [
                "// Generated by `scripts/export_timing_ocp.py`. Do not edit.",
                f"#ifndef {guard}",
                f"#define {guard}",
                "",
                f"#define CRANE_PLANNING_OCP_INTERVALS {int(parameters['ocp_intervals'])}",
                "// T = x[CRANE_PLANNING_OCP_X_HORIZON] * CRANE_PLANNING_OCP_HORIZON_S.",
                f"#define CRANE_PLANNING_OCP_X_HORIZON {X_HORIZON}",
                f"#define CRANE_PLANNING_OCP_HORIZON_S {float(parameters['ocp_horizon'])!r}",
                "",
                f"#define CRANE_PLANNING_OCP_H_SWAY {H_SWAY}",
                f"#define CRANE_PLANNING_OCP_H_FLOW {H_FLOW}",
                f"#define CRANE_PLANNING_OCP_NH {NH}",
                f"#define CRANE_PLANNING_OCP_HE_SWAY {HE_SWAY}",
                f"#define CRANE_PLANNING_OCP_HE_SWAY_RATE {HE_SWAY_RATE}",
                f"#define CRANE_PLANNING_OCP_NH_E {NH_E}",
                "",
                f"#define CRANE_PLANNING_OCP_SCALE {{{divisors}}}",
                "",
                f"#endif  // {guard}",
                "",
            ]
        )
    )
    return path


def generate(
    output: Path, descriptions: Path, parameters: dict, hydraulics: dict
) -> None:
    """Write the whole tree, from an empty directory."""
    output.mkdir(parents=True, exist_ok=True)
    ocp, scale, model = build_ocp(
        (descriptions / DESCRIPTION).read_text(), parameters, hydraulics
    )
    tree = ox.generate_solver(ocp, output)
    ox.write_output_map(model, ocp.model.name, tree)
    write_header(output, parameters, scale)
    ox.finalise(output, README)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ox.add_arguments(parser, PACKAGE)
    arguments = parser.parse_args()

    parameters = ox.read_ros_parameters(
        PACKAGE / "config" / "crane_planner.yaml", "crane_planner"
    )
    return ox.run(
        arguments.output,
        arguments.check,
        lambda output: generate(output, arguments.descriptions, parameters, parameters),
        "export_timing_ocp.py",
    )


if __name__ == "__main__":
    sys.exit(main())
