#!/usr/bin/env python3
"""
Code-generate the trajectory OCP that `crane_planning.ocp.build_ocp` defines.

Definition lives in crane_planning/ocp.py; this is only the command line and
the tree it writes -- a second copy here would drift.

    ./scripts/export_timing_ocp.py            # rewrite generated/
    ./scripts/export_timing_ocp.py --check    # regenerate into scratch, diff
    ./scripts/export_timing_ocp.py --description live.urdf --compile-only

Third compiles a solver for the machine on /robot_description, leaves
generated/ alone; without it the node refuses a description it wasn't baked
for. Dump that description first:

    ./scripts/dump_robot_description.py live.urdf
    ./scripts/export_timing_ocp.py --description live.urdf --compile-only
"""

from __future__ import annotations

import argparse
import dataclasses
import sys
from pathlib import Path

import numpy as np

PACKAGE = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PACKAGE.parent / "crane_ocp" / "scripts"))
sys.path.insert(0, str(PACKAGE))

import crane_ocp_export as ox  # noqa: E402
from acados_template import AcadosOcpSolver  # noqa: E402
from crane_planning.config import PlannerConfig  # noqa: E402
from crane_planning.ocp import (  # noqa: E402
    CACHE,
    DESCRIPTION,
    GENERATED_HEADER,
    H_ACCEL,
    H_COMMAND,
    H_FLOW,
    H_RATE,
    H_SWAY,
    HE_SWAY,
    HE_SWAY_RATE,
    NH,
    NH_E,
    SOLVER_NAME,
    X_HORIZON,
    build_ocp,
    cache_key,
    tree_of,
    write_manifest,
)

# What is committed, and so what `--check` compares file by file. The whole tree
# is written either way; everything outside this is gitignored and reaches the
# comparison through `CRANE_PLANNING_OCP_GENERATED_DIGEST`. The CasADi bodies are
# most of the tree and no review reads one.
REVIEWED = (
    "README.md",
    GENERATED_HEADER,
    f"{SOLVER_NAME}/acados_solver_{SOLVER_NAME}.h",
)

# -- generation --


README = """\
# generated

`scripts/export_timing_ocp.py` writes this tree. Do not edit it; re-run the
script. `--check` regenerates into a scratch tree and diffs;
`test/test_generated_is_current.py` runs it.

Three files are committed -- this README, `crane_planning_ocp_generated.h` and
`crane_planning_ocp_pzs100/acados_solver_crane_planning_ocp_pzs100.h`. The rest
is gitignored and reaches `--check` through
`CRANE_PLANNING_OCP_GENERATED_DIGEST` in the header: sha256 over every
uncommitted generated file, so a description edit that only moves the CasADi
bodies still fails.

The horizon, the weights `W`, every box and every `L1` slack price are set on the
generated solver at run time, so moving any of them needs no re-export. What is
baked is the **structure**: the residual rows and their scaling, the row order of
`h`, and the description the dynamics were built from.
"""


def write_header(
    output: Path, parameters: dict, scale: np.ndarray, tree_digest: str
) -> Path:
    """Write the row offsets and divisors the caller must agree with, not invent."""
    path = output / GENERATED_HEADER
    guard = "CRANE_PLANNING_OCP_GENERATED_H_"
    divisors = ", ".join(f"{value!r}" for value in scale.tolist())
    path.write_text(
        "\n".join(
            [
                "// Generated by `scripts/export_timing_ocp.py`. Do not edit.",
                f"#ifndef {guard}",
                f"#define {guard}",
                "",
                f"#define CRANE_PLANNING_OCP_INTERVALS {int(parameters['ocp_intervals'])}",
                "// T = x[CRANE_PLANNING_OCP_X_HORIZON] * CRANE_PLANNING_OCP_HORIZON_S.",
                f"#define CRANE_PLANNING_OCP_X_HORIZON {X_HORIZON}",
                f"#define CRANE_PLANNING_OCP_HORIZON_S {float(parameters['ocp_horizon'])!r}",
                "",
                f"#define CRANE_PLANNING_OCP_H_SWAY {H_SWAY}",
                f"#define CRANE_PLANNING_OCP_H_FLOW {H_FLOW}",
                f"#define CRANE_PLANNING_OCP_H_RATE {H_RATE}",
                f"#define CRANE_PLANNING_OCP_H_ACCEL {H_ACCEL}",
                f"#define CRANE_PLANNING_OCP_H_COMMAND {H_COMMAND}",
                f"#define CRANE_PLANNING_OCP_NH {NH}",
                f"#define CRANE_PLANNING_OCP_HE_SWAY {HE_SWAY}",
                f"#define CRANE_PLANNING_OCP_HE_SWAY_RATE {HE_SWAY_RATE}",
                f"#define CRANE_PLANNING_OCP_NH_E {NH_E}",
                "",
                f"#define CRANE_PLANNING_OCP_SCALE {{{divisors}}}",
                "",
                "// The rest of the tree, uncommitted: sha256 over every generated",
                "// file outside `REVIEWED`, on normalised content. A description or",
                "// hydraulics edit lands in the CasADi bodies and nothing else here,",
                "// so this is what `--check` gates them on.",
                f'#define CRANE_PLANNING_OCP_GENERATED_DIGEST "{tree_digest}"',
                "",
                f"#endif  // {guard}",
                "",
            ]
        )
    )
    return path


def generate(
    output: Path, description: str, parameters: dict, hydraulics: dict
) -> None:
    """Write the whole tree, from an empty directory."""
    output.mkdir(parents=True, exist_ok=True)
    ocp, scale, model = build_ocp(description, parameters, hydraulics)
    tree = ox.generate_solver(ocp, output)
    ox.write_output_map(model, ocp.model.name, tree)
    write_header(output, parameters, scale, ox.tree_digest(output, REVIEWED))
    ox.finalise(output, README)


def compile_solver(description: str, parameters: dict, hydraulics: dict) -> None:
    """
    Compile the solver into the cache the planner loads from.

    Without this the node refuses the description rather than pay code-gen +
    a C build (13 s warm, minutes cold) inside whatever asked for the plan.
    Second build_ocp/code-gen on purpose: output holds the text tree --check
    reviews; a compiled .so can't live there, so it's two artifacts.
    """
    ocp, _, _ = build_ocp(description, parameters, hydraulics)
    CACHE.mkdir(parents=True, exist_ok=True)
    # Cache key covers path_segments, integrator and description hash: cached
    # .so is loaded not compared, so any change must land in a new directory
    # or the node silently reuses the old build. Node hashes /robot_description
    # and reports a mismatch instead of answering silently wrong.
    key = cache_key(parameters, hydraulics, description)
    tree = tree_of(key)
    ocp.code_export_directory = str(tree)
    AcadosOcpSolver(ocp, json_file=str(tree.with_suffix(".json")), verbose=False)
    write_manifest(tree, key)
    print(f"compiled {tree} (description sha1 {key['description'][:10]})")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[1])
    ox.add_arguments(parser, PACKAGE)
    parser.add_argument(
        "--no-compile",
        action="store_true",
        help="write the tree but do not compile the solver into the cache",
    )
    parser.add_argument(
        "--description",
        type=Path,
        help=(
            "the machine to bake, instead of the test fixture. What the node "
            "plans for is whatever `/robot_description` carries, which in sim is "
            "a different xacro than the fixture; dump it byte for byte with "
            "`scripts/dump_robot_description.py`. Needs --compile-only"
        ),
    )
    parser.add_argument(
        "--compile-only",
        action="store_true",
        help=(
            "compile into the cache and leave `generated/` alone -- the prep "
            "step for a live description, which must not rewrite the shipped tree"
        ),
    )
    arguments = parser.parse_args()

    # yaml over the declared defaults, which is what the node's declaration does.
    # Not the yaml alone: `command_k`, `command_u_*` and `pump_flow_max` were moved
    # out of it into crane_model and are only reachable through `PlannerConfig`.
    parameters = {
        **dataclasses.asdict(PlannerConfig()),
        **ox.read_ros_parameters(
            PACKAGE / "config" / "crane_planner.yaml", "crane_planner"
        ),
    }
    source = arguments.description or arguments.descriptions / DESCRIPTION
    description = source.read_text()
    # generated/ is the shipped tree --check (and test_generated_is_current)
    # diffs against; writing another machine into it makes every later --check
    # report a spurious diff.
    if arguments.description and not arguments.compile_only:
        parser.error("--description writes only into the cache: add --compile-only")
    if arguments.compile_only:
        compile_solver(description, parameters, parameters)
        return 0
    status = ox.run(
        arguments.output,
        arguments.check,
        lambda output: generate(output, description, parameters, parameters),
        "export_timing_ocp.py",
        reviewed=REVIEWED,
    )
    # --check compares two trees and must not touch the cache; a real export
    # leaves a compiled solver so the node doesn't build one on demand.
    if status == 0 and not arguments.check and not arguments.no_compile:
        compile_solver(description, parameters, parameters)
    return status


if __name__ == "__main__":
    sys.exit(main())
